### ISSUE TITLE
Cannot discern between tests with long names that share a starting string

### ISSUE THREAD

**Issue by AArnott** [xunit/devices.xunit#33]
The font is so large, with no word wrap in the UI, that if I have two or more tests that all start with the same word or two, I can't discern between them. No UI I can find will display the full test name.

For example, here is a screenshot that demonstrates no test name is shown. When the test happens to fail I can usually figure out the test name from the stack trace. But when a test passed, or before I run it, I can't tell.

![missingformatmessage](https://cloud.githubusercontent.com/assets/3548/11378769/be53b874-92a1-11e5-96bc-ae50cad2c907.png)

**Comment by onovotny** [comment]
This is a partial dup of #28. 

I agree, def needs something better here. Smaller size and word-wrap.

**Comment by AArnott** [comment]
Ah yes, I'd say it's a dupe of #28. feel free to close unless you see something unique in this report.

**Comment by onovotny** [comment]
I'll keep this one open as dealing with the length of the test names. #28 also has an android component to it with the data being cleared on rotation

**Comment by onovotny** [comment]
I have a fix for the test result page for Wpa81/Xamarin, etc. That'll wrap the test name.

For UWP on the phone though, it can scroll if the text is too long, is that ok? Do you need wrapping there?

**Comment by AArnott** [comment]
Scrolling---as in I can drag with my finger horizontally? Yes, that's fine.

**Comment by onovotny** [comment]
Just pushed 46b3bfef8d63ccccec0179942d4acfa2270b35ba with the fix; should be in the devices CI feed in a few minutes.

**Comment by onovotny** [comment]
Fix is in current CI build and will be in next NuGet release

**Comment by AArnott** [comment]
Is this fixed for passing tests with no output?

**Comment by onovotny** [comment]
It should be in the next ci build, 11?

**Comment by AArnott** [comment]
cool. I'll check it out.

**Comment by kentcb** [comment]
Out of interest, does this also set iOS 9's `CellLayoutMarginsFollowReadableWidth` property to `false` because it ludicrously defaults to `true`, which breaks existing table views so that they are essentially squashed horizontally. Rotating my iPad to landscape mode does absolutely nothing anymore to help me see more of the test names.

**Comment by onovotny** [comment]
I'm not sure....all of the non-UWP UI is done by Xamarin Forms and I have no idea what it's iOS renderer does in this case.

What I did do was to not use the `Title` element of the `ContentPage` and instead use a separate `Label` within the `StackLayout`. That appears to have better wrapping characteristics. 

Always happy to take PR's to make things better (including any platform-specific Xam Forms renderers).

**Comment by kentcb** [comment]
OK, thanks @onovotny 

Yeah, XF doesn't override the default. The fact that this new property screws up existing app layouts when transitioning from iOS 8 to 9 leaves a bad taste in my mouth. They could easily (and more reasonably) added the property and made it opt-in. It's almost like Apple _want_ to force developers to maintain their license just to make minor changes to apps that would otherwise function just fine in iOS 9. Wait, no, it's _exactly_ like that.
